plugins:
  - '@semantic-release/commit-analyzer'
  - - '@semantic-release/exec'
    - successCmd: echo 'yes' >> .release
      failCmd: echo 'no' >> .release
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@semantic-release/npm'
    - npmPublish: false
  - '@semantic-release/github'
  - - '@codedependant/semantic-release-docker'
    - dockerImage: warframe-status
      dockerRegistry: ghcr.io
      dockerProject: wfcd
      dockerPlatform:
        - 'linux/amd64'
        - 'linux/arm64'
  - - '@semantic-release/git'
    - assets:
        - package.json
        - package-lock.json
        - CHANGELOG.md
  - '@eclass/semantic-release-sentry-releases'
branches: main
